### ISSUE TITLE
Build sending incorrect emails for master

### ISSUE THREAD

**Issue by AHumanFromCA** [zowe/zowe-cli#169]
A build of master just failed and sent out an email with the following contents:

```
Build Failure.

A build of master has finished.

The pipeline was unable to automatically bump the pre-release version in git. THIS IS LIKELY NOT AN ISSUE WITH THE BUILD as all the tests have to pass to get to this point.

Possible causes of this error:

A commit was made to master during the current run.
The user account tied to the build is no longer valid.
The remote server is experiencing issues.
THIS BUILD WILL BE MARKED AS A FAILURE AS WE CANNOT GUARENTEE THAT THE PROBLEM DOES NOT LIE IN THE BUILD AND CORRECTIVE ACTION MAY NEED TO TAKE PLACE.
Branch: master

Check console output at "brightside/master [204]"
```

However the build never made it to the test phase as the following error was present in the build:

```
[brightside_master-3AKV64GRSVY7DNSLB7W53EV7SMUJFFFGEJP3WKUK7U4JRYTDD5YQ] Running shell script

+ npm run build



> @brightside/core@2.0.0-next.201812132112 build /home/jenkins/workspace/brightside_master-3AKV64GRSVY7DNSLB7W53EV7SMUJFFFGEJP3WKUK7U4JRYTDD5YQ

> gulp updateLicense && tsc --pretty && npm run lint && npm run checkTestsCompile && madge -c lib



[15:05:05] Using gulpfile ~/workspace/brightside_master-3AKV64GRSVY7DNSLB7W53EV7SMUJFFFGEJP3WKUK7U4JRYTDD5YQ/gulpfile.js

[15:05:05] Starting 'updateLicense'...

[15:05:05] Ensured that 599 files had copyright information (599 already did).

[15:05:05] Finished 'updateLicense' after 193 ms



> @brightside/core@2.0.0-next.201812132112 lint /home/jenkins/workspace/brightside_master-3AKV64GRSVY7DNSLB7W53EV7SMUJFFFGEJP3WKUK7U4JRYTDD5YQ

> npm run lint:packages && npm run lint:tests





> @brightside/core@2.0.0-next.201812132112 lint:packages /home/jenkins/workspace/brightside_master-3AKV64GRSVY7DNSLB7W53EV7SMUJFFFGEJP3WKUK7U4JRYTDD5YQ

> tslint --format stylish -c ./tslint-packages.json "packages/**/*.ts"





> @brightside/core@2.0.0-next.201812132112 lint:tests /home/jenkins/workspace/brightside_master-3AKV64GRSVY7DNSLB7W53EV7SMUJFFFGEJP3WKUK7U4JRYTDD5YQ

> tslint --format stylish -c ./tslint-tests.json "**/__tests__/**/*.ts"





> @brightside/core@2.0.0-next.201812132112 checkTestsCompile /home/jenkins/workspace/brightside_master-3AKV64GRSVY7DNSLB7W53EV7SMUJFFFGEJP3WKUK7U4JRYTDD5YQ

> echo "Checking that test source compiles..." && tsc --project __tests__/test-tsconfig.json --noEmit 



Checking that test source compiles...

module.js:549

    throw err;

    ^



Error: Cannot find module 'eslint/lib/util/traverser'

    at Function.Module._resolveFilename (module.js:547:15)

    at Function.Module._load (module.js:474:25)

    at Module.require (module.js:596:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (/home/jenkins/workspace/brightside_master-3AKV64GRSVY7DNSLB7W53EV7SMUJFFFGEJP3WKUK7U4JRYTDD5YQ/node_modules/typescript-eslint-parser/parser.js:13:19)

    at Module._compile (module.js:652:30)

    at Object.Module._extensions..js (module.js:663:10)

    at Module.load (module.js:565:32)

    at tryModuleLoad (module.js:505:12)

    at Function.Module._load (module.js:497:3)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! @brightside/core@2.0.0-next.201812132112 build: `gulp updateLicense && tsc --pretty && npm run lint && npm run checkTestsCompile && madge -c lib`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the @brightside/core@2.0.0-next.201812132112 build script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     /home/jenkins/.npm/_logs/2019-01-08T15_05_22_957Z-debug.log

script returned exit code 1
```

This needs to be addressed so that we can get proper details about a failing run.

**Comment by ChrisBoehmCA** [comment]
Was this resolved with the migration to the new Jenkinsfile?

**Comment by AHumanFromCA** [comment]
I think this issue became invalid with the new changes. We didn't really fix it, we revamped how emails work entirely. Either way this can certainly be closed.

**Comment by ChrisBoehmCA** [comment]
Thanks
